### ISSUE TITLE
Turns on network speed

### ISSUE THREAD

**Issue by LauralHill** [KpChuck/K-Manager#3]
Added a theme for the status bar and automatically turned on the network speed option.

**Comment by KpChuck** [comment]
Have you tried turning the network speed option off and on again?

**Comment by LauralHill** [comment]
I mean, it turns off, I just want to keep it off.

**Comment by LauralHill** [comment]
OK I tried disabling the status bar, turning it off, then on, then off again. That seems to have fixed the problem.
