### ISSUE TITLE
error when changing icons to the left.

### ISSUE THREAD

**Issue by Die55** [KpChuck/K-Manager#7]
» [com.android.systemui]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//type2_Center:_Stock_Clock/layout/status_bar.xml:4: error: Error: No resource found that matches the given name (at 'layout' with value '@*com.android.systemui:layout/signal_cluster_view').
» [com.android.systemui]: Installation of "com.android.systemui" has failed.

**Comment by KpChuck** [comment]
[SystemUI.zip](https://github.com/KpChuck/K-Manager/files/2533280/SystemUI.zip)

**Comment by Die55** [comment]
It's a custom rom (havoc op3).
Thanks you.
Great work!

**Comment by KpChuck** [comment]
Fixed with https://github.com/KpChuck/K-Manager/commit/b7117be70ecadfc152b844e16d079bad3a2d0125
